// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz9MfohlXTZovyFlZJP1l6lm5SJsahV2E',
    appId: '1:377097585644:web:f9a07ab8debf3fc4bc36c9',
    messagingSenderId: '377097585644',
    projectId: 'flutter-rec-oct-2025-v3',
    authDomain: 'flutter-rec-oct-2025-v3.firebaseapp.com',
    storageBucket: 'flutter-rec-oct-2025-v3.firebasestorage.app',
    measurementId: 'G-2GN3J6135Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEULc3pSZl7aHj1RRMZR4mhKwL9RaW-Kk',
    appId: '1:377097585644:android:449f69c09b74b223bc36c9',
    messagingSenderId: '377097585644',
    projectId: 'flutter-rec-oct-2025-v3',
    storageBucket: 'flutter-rec-oct-2025-v3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiL0rWlGzQ0Rnoq7V9Z4kcjREGHMk1icI',
    appId: '1:377097585644:ios:f2aac911e79295fabc36c9',
    messagingSenderId: '377097585644',
    projectId: 'flutter-rec-oct-2025-v3',
    storageBucket: 'flutter-rec-oct-2025-v3.firebasestorage.app',
    iosBundleId: 'com.example.flutterRecOct2025V3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiL0rWlGzQ0Rnoq7V9Z4kcjREGHMk1icI',
    appId: '1:377097585644:ios:f2aac911e79295fabc36c9',
    messagingSenderId: '377097585644',
    projectId: 'flutter-rec-oct-2025-v3',
    storageBucket: 'flutter-rec-oct-2025-v3.firebasestorage.app',
    iosBundleId: 'com.example.flutterRecOct2025V3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz9MfohlXTZovyFlZJP1l6lm5SJsahV2E',
    appId: '1:377097585644:web:7fbda7996e52ed19bc36c9',
    messagingSenderId: '377097585644',
    projectId: 'flutter-rec-oct-2025-v3',
    authDomain: 'flutter-rec-oct-2025-v3.firebaseapp.com',
    storageBucket: 'flutter-rec-oct-2025-v3.firebasestorage.app',
    measurementId: 'G-WGSD5V1B96',
  );
}
